# Generated by Django 2.2.14 on 2020-08-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200731_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='pin',
            field=models.CharField(default='0000', max_length=12),
        ),
    ]
