# Generated by Django 2.2.14 on 2020-08-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200805_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
