# Generated by Django 2.2.14 on 2020-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200805_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='enter_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='regi_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
