# Generated by Django 2.2.14 on 2020-08-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_access_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='enter_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='access',
            name='recent',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='regi_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
