# Generated by Django 2.2.14 on 2020-08-12 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200812_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 13, 38, 59, 151111)),
        ),
    ]
