# Generated by Django 2.2.14 on 2020-08-12 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200812_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='enter_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 13, 41, 25, 540990)),
        ),
        migrations.AlterField(
            model_name='access',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 13, 41, 25, 540990)),
        ),
    ]
