# Generated by Django 2.2.14 on 2020-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('in_at', models.DateTimeField(auto_now_add=True)),
                ('out_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
